# Computing the SVD

Copyright (C) 2020 Andreas Kloeckner

<details>
<summary>MIT License</summary>
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
</details>

In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
np.random.seed(15)
n = 5
A = np.random.randn(n, n)

Now compute the eigenvalues and eigenvectors of $A^TA$ as `eigvals` and `eigvecs` using `la.eig` or `la.eigh` (symmetric):

In [11]:
#clear
eigvals, eigvecs = la.eigh(A.T @ A)

In [12]:
eigvals

array([0.08637178, 0.457892  , 2.04177547, 2.34383161, 8.37000184])

Eigenvalues are real and non-negative. Coincidence?

In [13]:
eigvecs.shape

(5, 5)

Check that those are in fact eigenvectors and eigenvalues:

In [14]:
#clear
B = A.T @ A
B - eigvecs @ np.diag(eigvals) @ la.inv(eigvecs)

array([[ 1.77635684e-15,  2.22044605e-15,  3.10862447e-15,
         8.88178420e-16,  8.88178420e-16],
       [ 2.22044605e-16, -8.88178420e-16,  0.00000000e+00,
        -8.88178420e-16,  2.63677968e-16],
       [-8.88178420e-16,  4.44089210e-16,  8.88178420e-16,
        -2.22044605e-16,  6.66133815e-16],
       [ 0.00000000e+00, -4.44089210e-16,  8.88178420e-16,
         0.00000000e+00,  7.77156117e-16],
       [ 0.00000000e+00, -9.02056208e-17,  3.88578059e-16,
         0.00000000e+00,  3.33066907e-16]])

`eigvecs` are orthonormal! (Why?)

Check:

In [15]:
#clear
la.norm(eigvecs.T @ eigvecs  - np.eye(n))

2.094158390904296e-15

------
Now piece together the SVD:

In [16]:
#clear
Sigma = np.diag(np.sqrt(eigvals))

In [17]:
#clear
V = eigvecs

In [18]:
#clear
U = A @ V @ la.inv(Sigma)

Check orthogonality of `U`:

In [19]:
#clear
U @ U.T - np.eye(n)

array([[-1.11022302e-15, -7.67324533e-16, -6.67804308e-16,
         1.47963782e-15,  1.44717415e-16],
       [-7.67324533e-16,  6.66133815e-16, -5.43672425e-16,
         6.51481016e-16, -2.64998805e-16],
       [-6.67804308e-16, -5.43672425e-16,  2.66453526e-15,
        -1.42306617e-15,  1.55464267e-15],
       [ 1.47963782e-15,  6.51481016e-16, -1.42306617e-15,
         3.10862447e-15, -1.13201575e-15],
       [ 1.44717415e-16, -2.64998805e-16,  1.55464267e-15,
        -1.13201575e-15,  4.44089210e-16]])